/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DirectoriesRouteImport } from './routes/directories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DirectoryIdRouteImport } from './routes/directory.$id'

const DirectoriesRoute = DirectoriesRouteImport.update({
  id: '/directories',
  path: '/directories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryIdRoute = DirectoryIdRouteImport.update({
  id: '/directory/$id',
  path: '/directory/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/directories': typeof DirectoriesRoute
  '/directory/$id': typeof DirectoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/directories': typeof DirectoriesRoute
  '/directory/$id': typeof DirectoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/directories': typeof DirectoriesRoute
  '/directory/$id': typeof DirectoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/directories' | '/directory/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/directories' | '/directory/$id'
  id: '__root__' | '/' | '/directories' | '/directory/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DirectoriesRoute: typeof DirectoriesRoute
  DirectoryIdRoute: typeof DirectoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/directories': {
      id: '/directories'
      path: '/directories'
      fullPath: '/directories'
      preLoaderRoute: typeof DirectoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/$id': {
      id: '/directory/$id'
      path: '/directory/$id'
      fullPath: '/directory/$id'
      preLoaderRoute: typeof DirectoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DirectoriesRoute: DirectoriesRoute,
  DirectoryIdRoute: DirectoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
